### ISSUE TITLE
Making mapstruct mapper not to initialize new object when there is null passed

### ISSUE THREAD

**Issue by KubaSlowikowski** [mapstruct/mapstruct-examples#112]
Hello!

Is there any solution for problem mentioned here?
[LINK](https://stackoverflow.com/questions/65347332/how-to-make-mapstruct-mappers-return-null-instead-of-new-objects-with-all-fields)

**Comment by filiphr** [comment]
@KubaSlowikowski please do not cross post. We are monitoring StackOverflow and we give answers in time.
