### ISSUE TITLE
IDEA kotlin plugin with spring beans

### ISSUE THREAD

**Issue by z0mb1ek** [mapstruct/mapstruct-examples#129]
Hi. I use kapt and mapstruct plugin for my kotlin spring boot project. But IDEA says that **Could not autowire. No beans of 'ProductMapper' type found** I need compile kotlin files and it starts working&

Earlier in java it worked like a charm

**Comment by filiphr** [comment]
Please do not use the issue tracker for asking questions, use [StackOverflow](https://stackoverflow.com/questions/tagged/mapstruct) or our [Gitter Room](https://gitter.im/mapstruct/mapstruct-users) instead.
