### ISSUE TITLE
How to using mapstruct and springboot bean together?

### ISSUE THREAD

**Issue by daidai21** [mapstruct/mapstruct-examples#130]
```java
@Mapper(componentModel = "spring")
public interface DemoConvert {
    public static DemoConvert INSTANCE = mappers.getMapper(DemoConvert.class);

    @AutoWired
    private PersonInfoSearchService personInfoSearchService;

    @Mapping(source = "id", target = "id")
    @Mapping(source = "id", target = "gender", expression = "java(personInfoSearchService.searchGenderById(id))")
    PersonDTO toPerson(TeacherDTO teacherDTO);
}
```

This demo result is `AutoWired` is not working. How to solve it? 

tks!

**Comment by filiphr** [comment]
Please do not use the issue tracker for asking questions. If you need to ask question you can use [StackOverflow](https://stackoverflow.com/questions/tagged/mapstruct) or ask in our [Gitter room](https://gitter.im/mapstruct/mapstruct-users).

The code you have shared does not even compile.
