### ISSUE TITLE
MapStruct + Lombok + QueryDsl + Gradle Compiled Error

### ISSUE THREAD

**Issue by tonyzhao93** [mapstruct/mapstruct-examples#133]
my project was successfully compiled before add mapstruct,  but now it doesn`t work . I guess it's because of the AnnotationProcessor configs

my build.gradle like this:

gradle : 6.9
 springBootVersion = '2.2.13.RELEASE'
querydsl 5.0.0

dependencies {
    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-parent', version: '2.2.13.RELEASE', ext: 'pom'

    api(
            "com.querydsl:querydsl-jpa:5.0.0"
    )

    annotationProcessor 'org.projectlombok:lombok:1.18.20'
    compileOnly 'org.projectlombok:lombok:1.18.20'

    annotationProcessor(
            platform("org.springframework.boot:spring-boot-dependencies:${springBootVersion}"),
            "javax.persistence:javax.persistence-api",
            "javax.annotation:javax.annotation-api",
            "org.projectlombok:lombok:1.18.20",
            "com.querydsl:querydsl-apt:5.0.0:jpa",
            "org.mapstruct:mapstruct-processor:1.4.2.Final",
            "org.projectlombok:lombok-mapstruct-binding:0.2.0"
    )

    compile group: 'com.querydsl', name: 'querydsl-jpa', version: '5.0.0'
    compile group: 'com.querydsl', name: 'querydsl-apt', version: '5.0.0'
    compile group: 'com.querydsl', name: 'querydsl-core', version: '5.0.0'
    compile group: 'com.querydsl', name: 'querydsl-sql', version: '5.0.0'

    compile group: 'org.mapstruct', name: 'mapstruct-jdk8', version: '1.4.2.Final'
    compile "org.mapstruct:mapstruct-processor:1.4.2.Final"
    compile "org.projectlombok:lombok-mapstruct-binding:0.2.0"

    compile("org.springframework.boot:spring-boot-starter-quartz:${springBootVersion}")

    compile("org.springframework.boot:spring-boot-starter-web:${springBootVersion}")
    compile("org.springframework.boot:spring-boot-starter-data-jpa:${springBootVersion}")
    compile("org.springframework.data:spring-data-commons:${springBootVersion}")
    compile("org.springframework.boot:spring-boot-starter-jdbc:${springBootVersion}")
    compile("org.springframework.boot:spring-boot-starter-websocket:${springBootVersion}")

}

Does anyone know how to configure it??

**Comment by filiphr** [comment]
@tonyzhao93 please do not use our issue tracker for asking question. If you have a question please ask it on StackOverflow or in our [Discussions](https://github.com/mapstruct/mapstruct/discussions)
