### ISSUE TITLE
【Lombok】@FieldNameConstants  not work

### ISSUE THREAD

**Issue by AppSkyBoy** [mapstruct/mapstruct-examples#139]
when use the @FieldNameConstants of Fields at mapstruct , compile not work

**Comment by filiphr** [comment]
Please check the MapStruct interop in the documentation for the `FieldNameConstants` https://projectlombok.org/features/experimental/FieldNameConstants.

If you want to know more have a look at https://github.com/projectlombok/lombok/issues/2991 and https://github.com/mapstruct/mapstruct/issues/2609.

**Comment by genglongsir** [comment]
试试这个
https://github.com/mapstruct/mapstruct/issues/2951#issuecomment-2613805761
