### ISSUE TITLE
KSP instead if KAPT

### ISSUE THREAD

**Issue by Daniel-Jacob** [mapstruct/mapstruct-examples#143]
Since kapt is in maintenance mode shouldn't there be support for using Kotlin symbollic processing API instead of KAPT? If so, could someone provide an example on how to do this?

**Comment by filiphr** [comment]
From my understanding of KSP we need to provide something from MapStruct side. It can't just use the existing `mapstruct-processor`. This means that we cannot currently provide an example. Please vote for and follow https://github.com/mapstruct/mapstruct/issues/2522 for more information about the integration of MapStruct with KSP
