### ISSUE TITLE
Provide example for using MapStruct on Maven test sources

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct-examples#21]
It seems not to work out of the box: http://stackoverflow.com/questions/42713870/mapstruct-mapper-in-src-test-java-not-generated-by-maven-build

**Comment by filiphr** [comment]
@gunnarmorling it didn't work for you as well? I quickly tried something yesterday and it seemed that it was working. 

In any case we can add some Mappers to the test sources as well

**Comment by gunnarmorling** [comment]
I didn't try, but I thought it'd be worth adding an example, so we can the
SO poster and potential others in the future to it.
