### ISSUE TITLE
ClassNotFoundException: Cannot find implementation for com.mytest.mapstructtest.UserMapper

### ISSUE THREAD

**Issue by nadjin** [mapstruct/mapstruct-examples#45]
IDE : intelij 2018.2
demo : mapstruct-on-gradle
run result :  Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: Cannot find implementation for org.mapstruct.example.SourceTargetMapper
why?

**Comment by filiphr** [comment]
How is your IntelliJ configured? Are you delegating the build to gradle or not?

**Comment by nadjin** [comment]
@filiphr  yes. the project has builded by gradle, InteliJ has installed mapstrcut support plugin. i have no idea now. help me~~

**Comment by VictorChow** [comment]
same problem .
`java.lang.ClassNotFoundException: Cannot find implementation for org.mapstruct.example.SourceTargetMapper`

**Comment by nadjin** [comment]
@filiphr this is my config. 
![1](https://user-images.githubusercontent.com/23130767/44703129-0e4ee500-aac9-11e8-8c10-2337a30ee7e3.png)
![2](https://user-images.githubusercontent.com/23130767/44703130-0e4ee500-aac9-11e8-8f8c-5e069fed915f.png)
![3](https://user-images.githubusercontent.com/23130767/44703131-0e4ee500-aac9-11e8-8b11-f10a7571dc72.png)

**Comment by VictorChow** [comment]
Add sourceSets in build.gradle, it works.
```groovy
sourceSets {
    main.java.srcDirs += "build/generated/source/apt/main"
}
```

**Comment by ft0907** [comment]
@VictorChow @nadjin   How do you solve this problem? I can now generate the implementation class, but I always prompt when injecting objects.
java.lang.ClassNotFoundException: Cannot find implementation

**Comment by VictorChow** [comment]
@ft0907  add generated folder into `sourceSets`

**Comment by ft0907** [comment]
@VictorChow  Thank you very much for your answer, but I do not have this folder path.  
I have generated class and corresponding java files in the /build/classes folder. Is there a problem with the path to generate files?

**Comment by VictorChow** [comment]
![screen shot 2018-08-28 at 5 02 06 pm](https://user-images.githubusercontent.com/14194569/44712792-2bdd7800-aae4-11e8-8aac-c46c360cc40b.png)
![screen shot 2018-08-28 at 5 00 41 pm](https://user-images.githubusercontent.com/14194569/44712798-2e3fd200-aae4-11e8-9f61-7d5903e6b0cc.png)

**Comment by nadjin** [comment]
@VictorChow  Thank U so much, I did but it doesn't work..   o(￣┰￣*)ゞ
`plugins {
    id 'java'
    id 'net.ltgt.apt' version '0.9'
}
apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'

dependencies {
    compile('org.springframework.boot:spring-boot-starter-web')
    compileOnly 'org.mapstruct:mapstruct-jdk8:1.2.0.Final', 'org.projectlombok:lombok:1.+'
    apt 'org.mapstruct:mapstruct-processor:1.2.0.Final', 'org.projectlombok:lombok:1.+'
}

_sourceSets {
    main.java.srcDirs += "build/generated/source/apt/main"
}_
`

**Comment by VictorChow** [comment]
@nadjin i use `gradle-4.10-all`

**Comment by nadjin** [comment]
@VictorChow Thank u. @filiphr  VictorChow show the path , you can do like this 
![1](https://user-images.githubusercontent.com/23130767/44723964-0ceede00-ab04-11e8-9777-5892e95a89f6.png)
![2](https://user-images.githubusercontent.com/23130767/44723966-0ceede00-ab04-11e8-88e2-e61fa3b0f331.png)

then add 
sourceSets {
main.java.srcDirs += "build/generated/source/apt/main"
}
in build.gradle  
i will try other way .

**Comment by ft0907** [comment]
It has been able to run normally, but it is actually a version of Lombok. 

dependencies {
     classpath 'io.franzbecker:gradle-lombok:1.11'
     classpath "net.ltgt.gradle:gradle-apt-plugin:0.18"
}
apply plugin: "net.ltgt.apt-eclipse"
apply plugin: 'io.franzbecker.gradle-lombok'

lombok {
	version = '1.18.0'
}

dependencies {
        compileOnly 'org.projectlombok:lombok'
        compile 'org.mapstruct:mapstruct-jdk8:1.3.0.Beta1'
	annotationProcessor 'org.mapstruct:mapstruct-processor:1.3.0.Beta1'
	annotationProcessor 'org.projectlombok:lombok'
}

sourceSets {
	main.java.srcDirs += "build/generated/source/apt/main"
}

It's similar to the @filiphr example, but requires additional configuration of sourceSets. Is there anywhere you can configure this path by default！！！

**Comment by filiphr** [comment]
In order for IntelliJ to be properly configured one needs to use the following plugin:

```
apply plugin: "net.ltgt.apt-idea"
```

You are all using the [gradle-apt-plugin](https://github.com/tbroyer/gradle-apt-plugin). I think that once you have this IntelliJ should be able to configure itself correctly.

**Comment by eapereira** [comment]
my project uses this path:

`sourceSets {
    main.java.srcDirs += "build/generated/source/annotationProcessor"
}
`

**Comment by bawantha** [comment]
any ideas for maven ?

**Comment by csankhala** [comment]
Following things worked for me in addition to sourceSet changes:

`@Mapper(componentModel = "jsr330")`

Add componentModel for Mapper class
