### ISSUE TITLE
Can't generate mapping method from non-iterable type to iterable type.

### ISSUE THREAD

**Issue by meenakshiGyanmote** [mapstruct/mapstruct-examples#46]
Your example shows mapping for a source having a list and target having a simple object, i get a exception as **"Can't generate mapping method from non-iterable type to iterable type."** where the source is having a simple object and the target contains the list of object. 

more details on the mappings:

Can't map property "packagexxx.OrganisationNameType name" to "java.util.List<packageyyy.NameType> name". Consider to declare/implement a mapping method: "java.util.List<packageyyy.NameType> map(packagexxx.OrganisationNameType value)".

Do you have a solution for it?

**Comment by sjaakd** [comment]
which example? Did you mean [this](https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-iterable-to-non-iterable) one?. I just fetched and compiled it and it compiled...

**Comment by meenakshiGyanmote** [comment]
Yes correct, I have a scenario where I have to map a simple object in source to a list, could you please provide an example for it.

**Comment by filiphr** [comment]
@meenakshiGyanmote did you open the link from @sjaakd? That is literally an examples for how to map non-iterable to iterable. You can use the same pattern to do the reverse
