### ISSUE TITLE
Add example of using Gradle Kotlin DSL

### ISSUE THREAD

**Issue by johanvergeer** [mapstruct/mapstruct-examples#47]
Would it be possible to add an example for Gradle Kotlin DSL to compile Kotlin Interfaces?

I have been trying to get it to work for a couple of hours now, but I don't have enough experience to make sense of all the difference resources I found online. 

The most significant resources I found so far: 

- http://mapstruct.org/news/2013-07-08-using-mapstruct-with-gradle/
- https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-kotlin
- https://github.com/gradle/kotlin-dsl/tree/master/samples/extra-properties
- https://github.com/gradle/kotlin-dsl/issues/650
- https://github.com/jnizet/gradle-kotlin-dsl-migration-guide

**Comment by sjaakd** [comment]
I'm not sure from my mobile, but I thought there is an example in our examples repo..

**Comment by johanvergeer** [comment]
Hoi Sjaak,

I found an example, but that one only contains a pom.xml and an example of Gradle, without Kotlin

https://github.com/sjaakd/mapstruct-examples/tree/master/mapstruct-kotlin
https://github.com/sjaakd/mapstruct-examples/blob/master/mapstruct-on-gradle/build.gradle

I'm having trouble with joining all of them together, but I would like to keep using Gradle Kotlin DSL for the project. If you can't provide it, I will have another look, but that will take a while.

**Comment by sjaakd** [comment]
> I'm having trouble with joining all of them together, but I would like to keep using Gradle Kotlin DSL for the project. If you can't provide it, I will have another look, but that will take a while.

I'm afraid I can 't help you either.. I'm not a gradle expert. But perhaps other users can. If you manage to find a solution, it might be interesting if you could contribute it to our examples repo to help others...
