### ISSUE TITLE
kotlin example - java.lang.Long does not have an accessible parameterless constructor

### ISSUE THREAD

**Issue by vb-dci** [mapstruct/mapstruct-examples#55]
Hi, I'm trying to define a custom mapping methods between different types. 

I have adjusted the PersonDto.kt and Person.kt on the [mapstruct kotlin-example](https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-kotlin) so that the phonenumber is stored once as a string and once as a long.

This is how my mapper looks like:
```
@Mapper
interface PersonConverter {

    @Mapping(source = "phoneNumber", target = "phone", qualifiedByName = ["PhoneToLong"])
    fun convertToDto(person: Person): PersonDto

    @Mapping(source = "phone", target = "phoneNumber", qualifiedByName = ["PhoneToString"] )
    fun convertToModel(personDto: PersonDto): Person

    @Named("PhoneToLong")
    fun phoneToLong(obj: String?): Long? {
        return 123L
    }

    @Named("PhoneToString")
    fun phoneToString(obj: Long?): String {
        return "123"
    }
}
```

I'm not sure if this is a kapt or Mapstruct problem. But the compiler throws this error:
` [ERROR] C:\dev\source\workspace\mapstruct-examples\mapstruct-kotlin\target\kaptStubs\compile\org\mapstruct\example\kotlin\converter\PersonConverter.java:21: error: java.lang.Long does not have an accessible parameterless constructor.
[ERROR]     public abstract java.lang.Long phoneToLong(@org.jetbrains.annotations.Nullable()
`

**Comment by titaniche** [comment]
So, how to solve this problem?

**Comment by filiphr** [comment]
There is nothing that we can do from the Java side. This is a known problem in Kotlin. Have a look at https://github.com/mapstruct/mapstruct/issues/1577. Kotlin has `@JvmDefault` annotation but that also doesn't work (see [KT-25960](https://youtrack.jetbrains.com/issue/KT-25960)). For the time being I would suggest that you use an abstract class instead of an interface.
