### ISSUE TITLE
file miss??

### ISSUE THREAD

**Issue by Tony-luorancx** [mapstruct/mapstruct-examples#58]
when I download the ZIP file and import to my IDE , I can not find some files
import org.mapstruct.example.protobuf.UserProtos.DepartmentDTO;
import org.mapstruct.example.protobuf.UserProtos.PermissionDTO;
import org.mapstruct.example.protobuf.UserProtos.UserDTO;
[UserMapper.txt](https://github.com/mapstruct/mapstruct-examples/files/2959577/UserMapper.txt)

**Comment by filiphr** [comment]
Those are the protobuf files. They are auto generated. If you run `mvn package` the files would be generated
