### ISSUE TITLE
Copy Nested list with conditional mapping

### ISSUE THREAD

**Issue by renoshtj** [mapstruct/mapstruct-examples#64]
I have a list of Address object with ID,Street name,City, PostalCode
and list of Contact object with ID, Street,City and Phone
Can i copy Street name and City alone 
from List<Contact> to List<Address> based on ID matching ?

Address Object already has ID and Postalcode.

**Comment by chris922** [comment]
Hey @renoshtj! It would be great if you can post the question on Stackoverflow using the [`mapstruct`](http://stackoverflow.com/questions/tagged/mapstruct) tag, in our [Gitter room](https://gitter.im/mapstruct/mapstruct-users) or [Google group](https://groups.google.com/forum/?fromgroups#!forum/mapstruct-users).

In case the described behaviour is not possible and you think it's worth adding it you can raise a new issue in our [mapstruct](https://github.com/mapstruct/mapstruct) repository with all required information.

Besides that a short example would be great (pseudocode should be enough).
