### ISSUE TITLE
mapstruct-kotlin example not working in IntelliJ IDEA with JDK 9+

### ISSUE THREAD

**Issue by SSilence** [mapstruct/mapstruct-examples#70]
Hi, I can not run the mapstruct-kotlin example on IntelliJ IDEA (and I have the same problem with my development project).

I'm using following setup:
mapstruct-kotlin example project (https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-kotlin)
OpenJDK 12
IntelliJ IDEA 2019.2
MapStruct 1.3.0.Final
Maven

Compiling with maven works. But run using IntelliJ IDEA run configuration "Application" will fail with following error:
Error:(3, 35) java: cannot find symbol
  symbol:   class Generated
  location: package javax.annotation.processing
Error:(7, 2) java: cannot find symbol
  symbol: class Generated

When I use MapStruct 1.2.0.Final it works without problem.

I think the problem is that the compilation will use JDK 12 with javax.annotation.processing.Generated but the IntelliJ run configuration uses JRE 8 where javax.annotation.Generated exists instead of javax.annotation.processing.Generated.

But I'm helpless how I can solve this problem. Using JDK 8 will work (because javax.annotation.Generated will be used, which is available on runtime). I would need an option (like mapstruct. suppressGeneratorTimestamp) where I can suppress the complete usage of generated annotation. Or where I can enforce the usage of the old javax.annotation.Generated annotation.

Thanks a lot!
 Tobi

**Comment by filiphr** [comment]
You can see all MapStruct [Configuration Options](http://mapstruct.org/documentation/stable/reference/html/#configuration-options) in the documentation. There is an example maven configuration there as well.

I am using JDK 11 and using maven works. I can do `mvn compile` and then can run the `Main`. However, if I do `mvn clean` then running the main doesn't work. Perhaps it is something with IntelliJ not invoking kapt.

You can't enforce the usage of `javax.annotation.Generated`. That depends on the availability of the annotation during the compilation. This depends on the source, target and release version of your sources.
