### ISSUE TITLE
JDK11 Couldn't find type java.sql.Date

### ISSUE THREAD

**Issue by colesico** [mapstruct/mapstruct-examples#71]
There is an error when use strict jpms module declaration :
Couldn't find type java.sql.Date. 

see issue #69 

it is reproduced when strict jpms module  (module-info.java) is present in the project

**Comment by colesico** [comment]
This can be fixed by adding "requires java.sql;" to jpms module-info but this is not correct way since there is no usage of java.sql module inside the project

**Comment by filiphr** [comment]
Thanks for the clarification @colesico. I reopened #69 and I'll close this one in favour of that one.
