### ISSUE TITLE
 Couldn't find type java.sql.Date. Are you missing a dependency on your classpath?

### ISSUE THREAD

**Issue by Krzysztof-Lempicki** [mapstruct/mapstruct-examples#81]
https://github.com/mapstruct/mapstruct-examples/blob/80f7843d74a6631edefacda7e478d1969d391a05/mapstruct-lombok/pom.xml#L54

When mapstruct processor is added to **pom** it causes compilation error in **IntelliJIdea**:

**Error:java: Couldn't find type java.sql.Date. Are you missing a dependency on your classpath?**

It makes problem even if build plugin is commented.

**Comment by Krzysztof-Lempicki** [comment]
migration to **1.4.0.Beta1** solved problem.

**Comment by filiphr** [comment]
Thanks for closing this. We had a dedicated issue in the core project, but it seems it wasn't linked and we forgot about this one
