### ISSUE TITLE
Is is possible to use  configuration files [json,xml]  to describe the mapping relation between fields?

### ISSUE THREAD

**Issue by murisans** [mapstruct/mapstruct-examples#87]

**Comment by filiphr** [comment]
Please use our [Gitter Room](https://gitter.im/mapstruct/mapstruct-users) or StackOverflow to ask questions. The issue tracker should not be used for asking questions.

To answer the question, no it is not possible. MapStruct is an annotation processor, which means, that it generates code during the compilation phase of project. You can however, write your own build plugins to achieve json / xml description that will generate the MapStruct mappers, and then our annotation processor will use that
